// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package ink

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type MetricTimeRange string

const (
	MetricTimeRangeFiveMinutes     MetricTimeRange = "FIVE_MINUTES"
	MetricTimeRangeOneHour         MetricTimeRange = "ONE_HOUR"
	MetricTimeRangeSixHours        MetricTimeRange = "SIX_HOURS"
	MetricTimeRangeTwentyFourHours MetricTimeRange = "TWENTY_FOUR_HOURS"
	MetricTimeRangeSevenDays       MetricTimeRange = "SEVEN_DAYS"
	MetricTimeRangeThirtyDays      MetricTimeRange = "THIRTY_DAYS"
)

var AllMetricTimeRange = []MetricTimeRange{
	MetricTimeRangeFiveMinutes,
	MetricTimeRangeOneHour,
	MetricTimeRangeSixHours,
	MetricTimeRangeTwentyFourHours,
	MetricTimeRangeSevenDays,
	MetricTimeRangeThirtyDays,
}

// __acceptInviteInput is used internally by genqlient
type __acceptInviteInput struct {
	Id string `json:"id"`
}

// GetId returns __acceptInviteInput.Id, and is useful for accessing the field via an interface.
func (v *__acceptInviteInput) GetId() string { return v.Id }

// __addDNSRecordInput is used internally by genqlient
type __addDNSRecordInput struct {
	Zone       string  `json:"zone"`
	Name       string  `json:"name"`
	RecordType string  `json:"recordType"`
	Content    string  `json:"content"`
	Ttl        *int    `json:"ttl"`
	Ws         *string `json:"ws"`
}

// GetZone returns __addDNSRecordInput.Zone, and is useful for accessing the field via an interface.
func (v *__addDNSRecordInput) GetZone() string { return v.Zone }

// GetName returns __addDNSRecordInput.Name, and is useful for accessing the field via an interface.
func (v *__addDNSRecordInput) GetName() string { return v.Name }

// GetRecordType returns __addDNSRecordInput.RecordType, and is useful for accessing the field via an interface.
func (v *__addDNSRecordInput) GetRecordType() string { return v.RecordType }

// GetContent returns __addDNSRecordInput.Content, and is useful for accessing the field via an interface.
func (v *__addDNSRecordInput) GetContent() string { return v.Content }

// GetTtl returns __addDNSRecordInput.Ttl, and is useful for accessing the field via an interface.
func (v *__addDNSRecordInput) GetTtl() *int { return v.Ttl }

// GetWs returns __addDNSRecordInput.Ws, and is useful for accessing the field via an interface.
func (v *__addDNSRecordInput) GetWs() *string { return v.Ws }

// __addDomainInput is used internally by genqlient
type __addDomainInput struct {
	Name    string  `json:"name"`
	Domain  string  `json:"domain"`
	Project *string `json:"project"`
	Ws      *string `json:"ws"`
}

// GetName returns __addDomainInput.Name, and is useful for accessing the field via an interface.
func (v *__addDomainInput) GetName() string { return v.Name }

// GetDomain returns __addDomainInput.Domain, and is useful for accessing the field via an interface.
func (v *__addDomainInput) GetDomain() string { return v.Domain }

// GetProject returns __addDomainInput.Project, and is useful for accessing the field via an interface.
func (v *__addDomainInput) GetProject() *string { return v.Project }

// GetWs returns __addDomainInput.Ws, and is useful for accessing the field via an interface.
func (v *__addDomainInput) GetWs() *string { return v.Ws }

// __createProjectInput is used internally by genqlient
type __createProjectInput struct {
	Input CreateProjectInput `json:"input"`
}

// GetInput returns __createProjectInput.Input, and is useful for accessing the field via an interface.
func (v *__createProjectInput) GetInput() CreateProjectInput { return v.Input }

// __createRepoInput is used internally by genqlient
type __createRepoInput struct {
	Input CreateRepoInput `json:"input"`
}

// GetInput returns __createRepoInput.Input, and is useful for accessing the field via an interface.
func (v *__createRepoInput) GetInput() CreateRepoInput { return v.Input }

// __createServiceInput is used internally by genqlient
type __createServiceInput struct {
	Input CreateServiceInput `json:"input"`
}

// GetInput returns __createServiceInput.Input, and is useful for accessing the field via an interface.
func (v *__createServiceInput) GetInput() CreateServiceInput { return v.Input }

// __createWorkspaceInput is used internally by genqlient
type __createWorkspaceInput struct {
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description"`
}

// GetName returns __createWorkspaceInput.Name, and is useful for accessing the field via an interface.
func (v *__createWorkspaceInput) GetName() string { return v.Name }

// GetSlug returns __createWorkspaceInput.Slug, and is useful for accessing the field via an interface.
func (v *__createWorkspaceInput) GetSlug() string { return v.Slug }

// GetDescription returns __createWorkspaceInput.Description, and is useful for accessing the field via an interface.
func (v *__createWorkspaceInput) GetDescription() *string { return v.Description }

// __declineInviteInput is used internally by genqlient
type __declineInviteInput struct {
	Id string `json:"id"`
}

// GetId returns __declineInviteInput.Id, and is useful for accessing the field via an interface.
func (v *__declineInviteInput) GetId() string { return v.Id }

// __deleteDNSRecordInput is used internally by genqlient
type __deleteDNSRecordInput struct {
	Zone     string  `json:"zone"`
	RecordId string  `json:"recordId"`
	Ws       *string `json:"ws"`
}

// GetZone returns __deleteDNSRecordInput.Zone, and is useful for accessing the field via an interface.
func (v *__deleteDNSRecordInput) GetZone() string { return v.Zone }

// GetRecordId returns __deleteDNSRecordInput.RecordId, and is useful for accessing the field via an interface.
func (v *__deleteDNSRecordInput) GetRecordId() string { return v.RecordId }

// GetWs returns __deleteDNSRecordInput.Ws, and is useful for accessing the field via an interface.
func (v *__deleteDNSRecordInput) GetWs() *string { return v.Ws }

// __deleteProjectInput is used internally by genqlient
type __deleteProjectInput struct {
	Slug string  `json:"slug"`
	Ws   *string `json:"ws"`
}

// GetSlug returns __deleteProjectInput.Slug, and is useful for accessing the field via an interface.
func (v *__deleteProjectInput) GetSlug() string { return v.Slug }

// GetWs returns __deleteProjectInput.Ws, and is useful for accessing the field via an interface.
func (v *__deleteProjectInput) GetWs() *string { return v.Ws }

// __deleteSecretsInput is used internally by genqlient
type __deleteSecretsInput struct {
	Input DeleteSecretsInput `json:"input"`
}

// GetInput returns __deleteSecretsInput.Input, and is useful for accessing the field via an interface.
func (v *__deleteSecretsInput) GetInput() DeleteSecretsInput { return v.Input }

// __deleteServiceInput is used internally by genqlient
type __deleteServiceInput struct {
	Name      *string `json:"name"`
	ServiceId *string `json:"serviceId"`
	Project   *string `json:"project"`
	ProjectId *string `json:"projectId"`
	Ws        *string `json:"ws"`
}

// GetName returns __deleteServiceInput.Name, and is useful for accessing the field via an interface.
func (v *__deleteServiceInput) GetName() *string { return v.Name }

// GetServiceId returns __deleteServiceInput.ServiceId, and is useful for accessing the field via an interface.
func (v *__deleteServiceInput) GetServiceId() *string { return v.ServiceId }

// GetProject returns __deleteServiceInput.Project, and is useful for accessing the field via an interface.
func (v *__deleteServiceInput) GetProject() *string { return v.Project }

// GetProjectId returns __deleteServiceInput.ProjectId, and is useful for accessing the field via an interface.
func (v *__deleteServiceInput) GetProjectId() *string { return v.ProjectId }

// GetWs returns __deleteServiceInput.Ws, and is useful for accessing the field via an interface.
func (v *__deleteServiceInput) GetWs() *string { return v.Ws }

// __deleteWorkspaceInput is used internally by genqlient
type __deleteWorkspaceInput struct {
	Id string `json:"id"`
}

// GetId returns __deleteWorkspaceInput.Id, and is useful for accessing the field via an interface.
func (v *__deleteWorkspaceInput) GetId() string { return v.Id }

// __deployTemplateInput is used internally by genqlient
type __deployTemplateInput struct {
	Input TemplateDeployInput `json:"input"`
}

// GetInput returns __deployTemplateInput.Input, and is useful for accessing the field via an interface.
func (v *__deployTemplateInput) GetInput() TemplateDeployInput { return v.Input }

// __execServiceInput is used internally by genqlient
type __execServiceInput struct {
	ServiceId *string `json:"serviceId"`
	Name      *string `json:"name"`
	Command   string  `json:"command"`
	Project   *string `json:"project"`
	Ws        *string `json:"ws"`
}

// GetServiceId returns __execServiceInput.ServiceId, and is useful for accessing the field via an interface.
func (v *__execServiceInput) GetServiceId() *string { return v.ServiceId }

// GetName returns __execServiceInput.Name, and is useful for accessing the field via an interface.
func (v *__execServiceInput) GetName() *string { return v.Name }

// GetCommand returns __execServiceInput.Command, and is useful for accessing the field via an interface.
func (v *__execServiceInput) GetCommand() string { return v.Command }

// GetProject returns __execServiceInput.Project, and is useful for accessing the field via an interface.
func (v *__execServiceInput) GetProject() *string { return v.Project }

// GetWs returns __execServiceInput.Ws, and is useful for accessing the field via an interface.
func (v *__execServiceInput) GetWs() *string { return v.Ws }

// __getRepoTokenInput is used internally by genqlient
type __getRepoTokenInput struct {
	Input GetRepoTokenInput `json:"input"`
}

// GetInput returns __getRepoTokenInput.Input, and is useful for accessing the field via an interface.
func (v *__getRepoTokenInput) GetInput() GetRepoTokenInput { return v.Input }

// __getServiceExecUrlInput is used internally by genqlient
type __getServiceExecUrlInput struct {
	ServiceId string `json:"serviceId"`
}

// GetServiceId returns __getServiceExecUrlInput.ServiceId, and is useful for accessing the field via an interface.
func (v *__getServiceExecUrlInput) GetServiceId() string { return v.ServiceId }

// __getServiceInput is used internally by genqlient
type __getServiceInput struct {
	Id string `json:"id"`
}

// GetId returns __getServiceInput.Id, and is useful for accessing the field via an interface.
func (v *__getServiceInput) GetId() string { return v.Id }

// __getServiceLogsInput is used internally by genqlient
type __getServiceLogsInput struct {
	Input LogsInput `json:"input"`
}

// GetInput returns __getServiceLogsInput.Input, and is useful for accessing the field via an interface.
func (v *__getServiceLogsInput) GetInput() LogsInput { return v.Input }

// __getServiceMetricsInput is used internally by genqlient
type __getServiceMetricsInput struct {
	ServiceId     string          `json:"serviceId"`
	TimeRange     MetricTimeRange `json:"timeRange"`
	MaxDataPoints *int            `json:"maxDataPoints"`
}

// GetServiceId returns __getServiceMetricsInput.ServiceId, and is useful for accessing the field via an interface.
func (v *__getServiceMetricsInput) GetServiceId() string { return v.ServiceId }

// GetTimeRange returns __getServiceMetricsInput.TimeRange, and is useful for accessing the field via an interface.
func (v *__getServiceMetricsInput) GetTimeRange() MetricTimeRange { return v.TimeRange }

// GetMaxDataPoints returns __getServiceMetricsInput.MaxDataPoints, and is useful for accessing the field via an interface.
func (v *__getServiceMetricsInput) GetMaxDataPoints() *int { return v.MaxDataPoints }

// __getUsageBillBreakdownInput is used internally by genqlient
type __getUsageBillBreakdownInput struct {
	Ws *string `json:"ws"`
}

// GetWs returns __getUsageBillBreakdownInput.Ws, and is useful for accessing the field via an interface.
func (v *__getUsageBillBreakdownInput) GetWs() *string { return v.Ws }

// __inviteToWorkspaceInput is used internally by genqlient
type __inviteToWorkspaceInput struct {
	Id   string  `json:"id"`
	User string  `json:"user"`
	Role *string `json:"role"`
}

// GetId returns __inviteToWorkspaceInput.Id, and is useful for accessing the field via an interface.
func (v *__inviteToWorkspaceInput) GetId() string { return v.Id }

// GetUser returns __inviteToWorkspaceInput.User, and is useful for accessing the field via an interface.
func (v *__inviteToWorkspaceInput) GetUser() string { return v.User }

// GetRole returns __inviteToWorkspaceInput.Role, and is useful for accessing the field via an interface.
func (v *__inviteToWorkspaceInput) GetRole() *string { return v.Role }

// __listDNSRecordsInput is used internally by genqlient
type __listDNSRecordsInput struct {
	Zone string  `json:"zone"`
	Ws   *string `json:"ws"`
}

// GetZone returns __listDNSRecordsInput.Zone, and is useful for accessing the field via an interface.
func (v *__listDNSRecordsInput) GetZone() string { return v.Zone }

// GetWs returns __listDNSRecordsInput.Ws, and is useful for accessing the field via an interface.
func (v *__listDNSRecordsInput) GetWs() *string { return v.Ws }

// __listDNSZonesInput is used internally by genqlient
type __listDNSZonesInput struct {
	Ws *string `json:"ws"`
}

// GetWs returns __listDNSZonesInput.Ws, and is useful for accessing the field via an interface.
func (v *__listDNSZonesInput) GetWs() *string { return v.Ws }

// __listProjectsInput is used internally by genqlient
type __listProjectsInput struct {
	Ws *string `json:"ws"`
}

// GetWs returns __listProjectsInput.Ws, and is useful for accessing the field via an interface.
func (v *__listProjectsInput) GetWs() *string { return v.Ws }

// __listServicesInput is used internally by genqlient
type __listServicesInput struct {
	Ws   *string `json:"ws"`
	Proj *string `json:"proj"`
}

// GetWs returns __listServicesInput.Ws, and is useful for accessing the field via an interface.
func (v *__listServicesInput) GetWs() *string { return v.Ws }

// GetProj returns __listServicesInput.Proj, and is useful for accessing the field via an interface.
func (v *__listServicesInput) GetProj() *string { return v.Proj }

// __listTemplateInstancesInput is used internally by genqlient
type __listTemplateInstancesInput struct {
	Project   *string `json:"project"`
	ProjectId *string `json:"projectId"`
	Ws        *string `json:"ws"`
}

// GetProject returns __listTemplateInstancesInput.Project, and is useful for accessing the field via an interface.
func (v *__listTemplateInstancesInput) GetProject() *string { return v.Project }

// GetProjectId returns __listTemplateInstancesInput.ProjectId, and is useful for accessing the field via an interface.
func (v *__listTemplateInstancesInput) GetProjectId() *string { return v.ProjectId }

// GetWs returns __listTemplateInstancesInput.Ws, and is useful for accessing the field via an interface.
func (v *__listTemplateInstancesInput) GetWs() *string { return v.Ws }

// __listTemplatesInput is used internally by genqlient
type __listTemplatesInput struct {
	Search *string `json:"search"`
}

// GetSearch returns __listTemplatesInput.Search, and is useful for accessing the field via an interface.
func (v *__listTemplatesInput) GetSearch() *string { return v.Search }

// __listWorkspaceInvitesInput is used internally by genqlient
type __listWorkspaceInvitesInput struct {
	Slug string `json:"slug"`
}

// GetSlug returns __listWorkspaceInvitesInput.Slug, and is useful for accessing the field via an interface.
func (v *__listWorkspaceInvitesInput) GetSlug() string { return v.Slug }

// __listWorkspaceMembersInput is used internally by genqlient
type __listWorkspaceMembersInput struct {
	Slug string `json:"slug"`
}

// GetSlug returns __listWorkspaceMembersInput.Slug, and is useful for accessing the field via an interface.
func (v *__listWorkspaceMembersInput) GetSlug() string { return v.Slug }

// __readChatInput is used internally by genqlient
type __readChatInput struct {
	Ws      string  `json:"ws"`
	Channel *string `json:"channel"`
	Cursor  *int    `json:"cursor"`
	Limit   *int    `json:"limit"`
}

// GetWs returns __readChatInput.Ws, and is useful for accessing the field via an interface.
func (v *__readChatInput) GetWs() string { return v.Ws }

// GetChannel returns __readChatInput.Channel, and is useful for accessing the field via an interface.
func (v *__readChatInput) GetChannel() *string { return v.Channel }

// GetCursor returns __readChatInput.Cursor, and is useful for accessing the field via an interface.
func (v *__readChatInput) GetCursor() *int { return v.Cursor }

// GetLimit returns __readChatInput.Limit, and is useful for accessing the field via an interface.
func (v *__readChatInput) GetLimit() *int { return v.Limit }

// __removeDomainInput is used internally by genqlient
type __removeDomainInput struct {
	Name    string  `json:"name"`
	Project *string `json:"project"`
	Ws      *string `json:"ws"`
}

// GetName returns __removeDomainInput.Name, and is useful for accessing the field via an interface.
func (v *__removeDomainInput) GetName() string { return v.Name }

// GetProject returns __removeDomainInput.Project, and is useful for accessing the field via an interface.
func (v *__removeDomainInput) GetProject() *string { return v.Project }

// GetWs returns __removeDomainInput.Ws, and is useful for accessing the field via an interface.
func (v *__removeDomainInput) GetWs() *string { return v.Ws }

// __removeWorkspaceMemberInput is used internally by genqlient
type __removeWorkspaceMemberInput struct {
	WsId   string `json:"wsId"`
	UserId string `json:"userId"`
}

// GetWsId returns __removeWorkspaceMemberInput.WsId, and is useful for accessing the field via an interface.
func (v *__removeWorkspaceMemberInput) GetWsId() string { return v.WsId }

// GetUserId returns __removeWorkspaceMemberInput.UserId, and is useful for accessing the field via an interface.
func (v *__removeWorkspaceMemberInput) GetUserId() string { return v.UserId }

// __revokeInviteInput is used internally by genqlient
type __revokeInviteInput struct {
	Id string `json:"id"`
}

// GetId returns __revokeInviteInput.Id, and is useful for accessing the field via an interface.
func (v *__revokeInviteInput) GetId() string { return v.Id }

// __sendChatMessageInput is used internally by genqlient
type __sendChatMessageInput struct {
	Ws      string  `json:"ws"`
	Channel *string `json:"channel"`
	Content string  `json:"content"`
}

// GetWs returns __sendChatMessageInput.Ws, and is useful for accessing the field via an interface.
func (v *__sendChatMessageInput) GetWs() string { return v.Ws }

// GetChannel returns __sendChatMessageInput.Channel, and is useful for accessing the field via an interface.
func (v *__sendChatMessageInput) GetChannel() *string { return v.Channel }

// GetContent returns __sendChatMessageInput.Content, and is useful for accessing the field via an interface.
func (v *__sendChatMessageInput) GetContent() string { return v.Content }

// __setSecretsInput is used internally by genqlient
type __setSecretsInput struct {
	Input SetSecretsInput `json:"input"`
}

// GetInput returns __setSecretsInput.Input, and is useful for accessing the field via an interface.
func (v *__setSecretsInput) GetInput() SetSecretsInput { return v.Input }

// __updateServiceInput is used internally by genqlient
type __updateServiceInput struct {
	Input UpdateServiceInput `json:"input"`
}

// GetInput returns __updateServiceInput.Input, and is useful for accessing the field via an interface.
func (v *__updateServiceInput) GetInput() UpdateServiceInput { return v.Input }

// acceptInviteResponse is returned by acceptInvite on success.
type acceptInviteResponse struct {
	// Accept a pending workspace invite and join as a member.
	WorkspaceAcceptInvite bool `json:"workspaceAcceptInvite"`
}

// GetWorkspaceAcceptInvite returns acceptInviteResponse.WorkspaceAcceptInvite, and is useful for accessing the field via an interface.
func (v *acceptInviteResponse) GetWorkspaceAcceptInvite() bool { return v.WorkspaceAcceptInvite }

// addDNSRecordResponse is returned by addDNSRecord on success.
type addDNSRecordResponse struct {
	// Add a DNS record to a zone. Supported types: A, AAAA, CNAME, MX, TXT, CAA. Managed records cannot be overwritten.
	DnsAddRecord ZoneRecord `json:"dnsAddRecord"`
}

// GetDnsAddRecord returns addDNSRecordResponse.DnsAddRecord, and is useful for accessing the field via an interface.
func (v *addDNSRecordResponse) GetDnsAddRecord() ZoneRecord { return v.DnsAddRecord }

// addDomainResponse is returned by addDomain on success.
type addDomainResponse struct {
	// Attach a custom domain to a service. The domain must be under a verified delegated zone. Auto-creates the required DNS records.
	DomainAdd AddDomainResult `json:"domainAdd"`
}

// GetDomainAdd returns addDomainResponse.DomainAdd, and is useful for accessing the field via an interface.
func (v *addDomainResponse) GetDomainAdd() AddDomainResult { return v.DomainAdd }

// createProjectResponse is returned by createProject on success.
type createProjectResponse struct {
	// Create a new project in a workspace.
	ProjectCreate Project `json:"projectCreate"`
}

// GetProjectCreate returns createProjectResponse.ProjectCreate, and is useful for accessing the field via an interface.
func (v *createProjectResponse) GetProjectCreate() Project { return v.ProjectCreate }

// createRepoResponse is returned by createRepo on success.
type createRepoResponse struct {
	// Create a git repository. Use host='ink' (default) for instant private repos on Ink's internal git, or host='github' to create on GitHub (requires GitHub OAuth). Returns a git remote URL with embedded push token.
	RepoCreate CreateRepoResult `json:"repoCreate"`
}

// GetRepoCreate returns createRepoResponse.RepoCreate, and is useful for accessing the field via an interface.
func (v *createRepoResponse) GetRepoCreate() CreateRepoResult { return v.RepoCreate }

// createServiceResponse is returned by createService on success.
type createServiceResponse struct {
	// Create a service and trigger its first deployment. The subdomain becomes {subdomain}.ml.ink. Returns immediately while build runs async — poll serviceGet to track status.
	ServiceCreate CreateServiceResult `json:"serviceCreate"`
}

// GetServiceCreate returns createServiceResponse.ServiceCreate, and is useful for accessing the field via an interface.
func (v *createServiceResponse) GetServiceCreate() CreateServiceResult { return v.ServiceCreate }

// createWorkspaceResponse is returned by createWorkspace on success.
type createWorkspaceResponse struct {
	// Create a new workspace for team collaboration. The creator becomes the owner.
	WorkspaceCreate Workspace `json:"workspaceCreate"`
}

// GetWorkspaceCreate returns createWorkspaceResponse.WorkspaceCreate, and is useful for accessing the field via an interface.
func (v *createWorkspaceResponse) GetWorkspaceCreate() Workspace { return v.WorkspaceCreate }

// declineInviteResponse is returned by declineInvite on success.
type declineInviteResponse struct {
	// Decline a pending workspace invite.
	WorkspaceDeclineInvite bool `json:"workspaceDeclineInvite"`
}

// GetWorkspaceDeclineInvite returns declineInviteResponse.WorkspaceDeclineInvite, and is useful for accessing the field via an interface.
func (v *declineInviteResponse) GetWorkspaceDeclineInvite() bool { return v.WorkspaceDeclineInvite }

// deleteDNSRecordResponse is returned by deleteDNSRecord on success.
type deleteDNSRecordResponse struct {
	// Delete a DNS record. Managed records (auto-created for custom domains) cannot be deleted.
	DnsDeleteRecord bool `json:"dnsDeleteRecord"`
}

// GetDnsDeleteRecord returns deleteDNSRecordResponse.DnsDeleteRecord, and is useful for accessing the field via an interface.
func (v *deleteDNSRecordResponse) GetDnsDeleteRecord() bool { return v.DnsDeleteRecord }

// deleteProjectResponse is returned by deleteProject on success.
type deleteProjectResponse struct {
	// Delete a project and all its services. Requires owner or admin role. Cannot delete the 'default' project.
	ProjectDelete bool `json:"projectDelete"`
}

// GetProjectDelete returns deleteProjectResponse.ProjectDelete, and is useful for accessing the field via an interface.
func (v *deleteProjectResponse) GetProjectDelete() bool { return v.ProjectDelete }

// deleteSecretsResponse is returned by deleteSecrets on success.
type deleteSecretsResponse struct {
	// Remove specific env var keys from a service. Triggers a redeploy.
	ServiceDeleteSecrets SetSecretsResult `json:"serviceDeleteSecrets"`
}

// GetServiceDeleteSecrets returns deleteSecretsResponse.ServiceDeleteSecrets, and is useful for accessing the field via an interface.
func (v *deleteSecretsResponse) GetServiceDeleteSecrets() SetSecretsResult {
	return v.ServiceDeleteSecrets
}

// deleteServiceResponse is returned by deleteService on success.
type deleteServiceResponse struct {
	// Permanently delete a service and tear down its container, DNS, and custom domain.
	ServiceDelete DeleteServiceResult `json:"serviceDelete"`
}

// GetServiceDelete returns deleteServiceResponse.ServiceDelete, and is useful for accessing the field via an interface.
func (v *deleteServiceResponse) GetServiceDelete() DeleteServiceResult { return v.ServiceDelete }

// deleteWorkspaceResponse is returned by deleteWorkspace on success.
type deleteWorkspaceResponse struct {
	// Delete a workspace. Must have no active services. Cannot delete your personal workspace.
	WorkspaceDelete bool `json:"workspaceDelete"`
}

// GetWorkspaceDelete returns deleteWorkspaceResponse.WorkspaceDelete, and is useful for accessing the field via an interface.
func (v *deleteWorkspaceResponse) GetWorkspaceDelete() bool { return v.WorkspaceDelete }

// deployTemplateResponse is returned by deployTemplate on success.
type deployTemplateResponse struct {
	// Deploy a template and return curated outputs plus the service graph.
	TemplateDeploy TemplateDeployResult `json:"templateDeploy"`
}

// GetTemplateDeploy returns deployTemplateResponse.TemplateDeploy, and is useful for accessing the field via an interface.
func (v *deployTemplateResponse) GetTemplateDeploy() TemplateDeployResult { return v.TemplateDeploy }

// execServiceResponse is returned by execService on success.
type execServiceResponse struct {
	// Run a command in a running service container and return the output. Max 30s timeout, 1MiB output.
	ServiceExec ExecResult `json:"serviceExec"`
}

// GetServiceExec returns execServiceResponse.ServiceExec, and is useful for accessing the field via an interface.
func (v *execServiceResponse) GetServiceExec() ExecResult { return v.ServiceExec }

// getAccountStatusResponse is returned by getAccountStatus on success.
type getAccountStatusResponse struct {
	// Current user's account: identity, GitHub App status, and default workspace slug.
	AccountStatus *AccountStatus `json:"accountStatus"`
}

// GetAccountStatus returns getAccountStatusResponse.AccountStatus, and is useful for accessing the field via an interface.
func (v *getAccountStatusResponse) GetAccountStatus() *AccountStatus { return v.AccountStatus }

// getRepoTokenResponse is returned by getRepoToken on success.
type getRepoTokenResponse struct {
	// Get a temporary push token for an existing repo. Tokens expire — call again when expired. The returned gitRemote URL has the token embedded for direct git push.
	RepoGetToken GetRepoTokenResult `json:"repoGetToken"`
}

// GetRepoGetToken returns getRepoTokenResponse.RepoGetToken, and is useful for accessing the field via an interface.
func (v *getRepoTokenResponse) GetRepoGetToken() GetRepoTokenResult { return v.RepoGetToken }

// getServiceExecUrlResponse is returned by getServiceExecUrl on success.
type getServiceExecUrlResponse struct {
	// Get a WebSocket URL for an interactive shell session into a running service. Connect to the returned URL with your auth token.
	ServiceExecUrl ExecSession `json:"serviceExecUrl"`
}

// GetServiceExecUrl returns getServiceExecUrlResponse.ServiceExecUrl, and is useful for accessing the field via an interface.
func (v *getServiceExecUrlResponse) GetServiceExecUrl() ExecSession { return v.ServiceExecUrl }

// getServiceLogsResponse is returned by getServiceLogs on success.
type getServiceLogsResponse struct {
	ServiceLogs LogsResult `json:"serviceLogs"`
}

// GetServiceLogs returns getServiceLogsResponse.ServiceLogs, and is useful for accessing the field via an interface.
func (v *getServiceLogsResponse) GetServiceLogs() LogsResult { return v.ServiceLogs }

// getServiceMetricsResponse is returned by getServiceMetrics on success.
type getServiceMetricsResponse struct {
	ServiceMetrics ServiceMetrics `json:"serviceMetrics"`
}

// GetServiceMetrics returns getServiceMetricsResponse.ServiceMetrics, and is useful for accessing the field via an interface.
func (v *getServiceMetricsResponse) GetServiceMetrics() ServiceMetrics { return v.ServiceMetrics }

// getServiceResponse is returned by getService on success.
type getServiceResponse struct {
	// Full details for a single service including config, env vars, custom domain, and deployment status.
	ServiceGet *Service `json:"serviceGet"`
}

// GetServiceGet returns getServiceResponse.ServiceGet, and is useful for accessing the field via an interface.
func (v *getServiceResponse) GetServiceGet() *Service { return v.ServiceGet }

// getUsageBillBreakdownResponse is returned by getUsageBillBreakdown on success.
type getUsageBillBreakdownResponse struct {
	UsageBillBreakdown UsageBillBreakdown `json:"usageBillBreakdown"`
}

// GetUsageBillBreakdown returns getUsageBillBreakdownResponse.UsageBillBreakdown, and is useful for accessing the field via an interface.
func (v *getUsageBillBreakdownResponse) GetUsageBillBreakdown() UsageBillBreakdown {
	return v.UsageBillBreakdown
}

// inviteToWorkspaceResponse is returned by inviteToWorkspace on success.
type inviteToWorkspaceResponse struct {
	// Invite a user by email or username. Invitee must accept before joining.
	WorkspaceInvite WorkspaceInvite `json:"workspaceInvite"`
}

// GetWorkspaceInvite returns inviteToWorkspaceResponse.WorkspaceInvite, and is useful for accessing the field via an interface.
func (v *inviteToWorkspaceResponse) GetWorkspaceInvite() WorkspaceInvite { return v.WorkspaceInvite }

// listDNSRecordsResponse is returned by listDNSRecords on success.
type listDNSRecordsResponse struct {
	// List all DNS records in a zone. Includes both user-created and managed (system) records.
	DnsListRecords []ZoneRecord `json:"dnsListRecords"`
}

// GetDnsListRecords returns listDNSRecordsResponse.DnsListRecords, and is useful for accessing the field via an interface.
func (v *listDNSRecordsResponse) GetDnsListRecords() []ZoneRecord { return v.DnsListRecords }

// listDNSZonesResponse is returned by listDNSZones on success.
type listDNSZonesResponse struct {
	// List all delegated DNS zones in a workspace with their verification status.
	DnsListZones []DNSZone `json:"dnsListZones"`
}

// GetDnsListZones returns listDNSZonesResponse.DnsListZones, and is useful for accessing the field via an interface.
func (v *listDNSZonesResponse) GetDnsListZones() []DNSZone { return v.DnsListZones }

// listMyInvitesResponse is returned by listMyInvites on success.
type listMyInvitesResponse struct {
	// List the current user's pending incoming invites across all workspaces.
	WorkspaceListMyInvites []WorkspaceInvite `json:"workspaceListMyInvites"`
}

// GetWorkspaceListMyInvites returns listMyInvitesResponse.WorkspaceListMyInvites, and is useful for accessing the field via an interface.
func (v *listMyInvitesResponse) GetWorkspaceListMyInvites() []WorkspaceInvite {
	return v.WorkspaceListMyInvites
}

// listProjectsProjectListProjectConnection includes the requested fields of the GraphQL type ProjectConnection.
type listProjectsProjectListProjectConnection struct {
	Nodes []Project `json:"nodes"`
}

// GetNodes returns listProjectsProjectListProjectConnection.Nodes, and is useful for accessing the field via an interface.
func (v *listProjectsProjectListProjectConnection) GetNodes() []Project { return v.Nodes }

// listProjectsResponse is returned by listProjects on success.
type listProjectsResponse struct {
	// Paginated list of projects in a workspace. Each project contains services and resources.
	ProjectList listProjectsProjectListProjectConnection `json:"projectList"`
}

// GetProjectList returns listProjectsResponse.ProjectList, and is useful for accessing the field via an interface.
func (v *listProjectsResponse) GetProjectList() listProjectsProjectListProjectConnection {
	return v.ProjectList
}

// listServicesResponse is returned by listServices on success.
type listServicesResponse struct {
	// Paginated list of all services in a workspace. Returns status from the latest deployment.
	ServiceList listServicesServiceListServiceConnection `json:"serviceList"`
}

// GetServiceList returns listServicesResponse.ServiceList, and is useful for accessing the field via an interface.
func (v *listServicesResponse) GetServiceList() listServicesServiceListServiceConnection {
	return v.ServiceList
}

// listServicesServiceListServiceConnection includes the requested fields of the GraphQL type ServiceConnection.
type listServicesServiceListServiceConnection struct {
	Nodes []Service `json:"nodes"`
}

// GetNodes returns listServicesServiceListServiceConnection.Nodes, and is useful for accessing the field via an interface.
func (v *listServicesServiceListServiceConnection) GetNodes() []Service { return v.Nodes }

// listTemplateInstancesResponse is returned by listTemplateInstances on success.
type listTemplateInstancesResponse struct {
	// List deployed template instances for a project. Sensitive outputs are masked in list responses.
	TemplateInstanceList []TemplateInstance `json:"templateInstanceList"`
}

// GetTemplateInstanceList returns listTemplateInstancesResponse.TemplateInstanceList, and is useful for accessing the field via an interface.
func (v *listTemplateInstancesResponse) GetTemplateInstanceList() []TemplateInstance {
	return v.TemplateInstanceList
}

// listTemplatesResponse is returned by listTemplates on success.
type listTemplatesResponse struct {
	// List available service templates. Optionally search by name, slug, tag, or description.
	TemplateList []Template `json:"templateList"`
}

// GetTemplateList returns listTemplatesResponse.TemplateList, and is useful for accessing the field via an interface.
func (v *listTemplatesResponse) GetTemplateList() []Template { return v.TemplateList }

// listWorkspaceInvitesResponse is returned by listWorkspaceInvites on success.
type listWorkspaceInvitesResponse struct {
	// List pending outgoing invites for a workspace. Requires admin or owner role.
	WorkspaceListInvites []WorkspaceInvite `json:"workspaceListInvites"`
}

// GetWorkspaceListInvites returns listWorkspaceInvitesResponse.WorkspaceListInvites, and is useful for accessing the field via an interface.
func (v *listWorkspaceInvitesResponse) GetWorkspaceListInvites() []WorkspaceInvite {
	return v.WorkspaceListInvites
}

// listWorkspaceMembersResponse is returned by listWorkspaceMembers on success.
type listWorkspaceMembersResponse struct {
	// List all members of a workspace with their roles and profile info.
	WorkspaceListMembers []WorkspaceMember `json:"workspaceListMembers"`
}

// GetWorkspaceListMembers returns listWorkspaceMembersResponse.WorkspaceListMembers, and is useful for accessing the field via an interface.
func (v *listWorkspaceMembersResponse) GetWorkspaceListMembers() []WorkspaceMember {
	return v.WorkspaceListMembers
}

// listWorkspacesResponse is returned by listWorkspaces on success.
type listWorkspacesResponse struct {
	// List all workspaces the user belongs to (owned and invited). Includes billing status for each.
	WorkspaceList []Workspace `json:"workspaceList"`
}

// GetWorkspaceList returns listWorkspacesResponse.WorkspaceList, and is useful for accessing the field via an interface.
func (v *listWorkspacesResponse) GetWorkspaceList() []Workspace { return v.WorkspaceList }

// readChatResponse is returned by readChat on success.
type readChatResponse struct {
	// Read messages from workspace chat. Supports cursor-based pagination. Omit channel for workspace-wide messages, or set to a project slug for project-scoped chat.
	ChatRead ReadChatResult `json:"chatRead"`
}

// GetChatRead returns readChatResponse.ChatRead, and is useful for accessing the field via an interface.
func (v *readChatResponse) GetChatRead() ReadChatResult { return v.ChatRead }

// removeDomainResponse is returned by removeDomain on success.
type removeDomainResponse struct {
	// Remove a custom domain from a service and clean up its managed DNS records.
	DomainRemove RemoveDomainResult `json:"domainRemove"`
}

// GetDomainRemove returns removeDomainResponse.DomainRemove, and is useful for accessing the field via an interface.
func (v *removeDomainResponse) GetDomainRemove() RemoveDomainResult { return v.DomainRemove }

// removeWorkspaceMemberResponse is returned by removeWorkspaceMember on success.
type removeWorkspaceMemberResponse struct {
	// Remove a member from a workspace. Requires admin or owner role. Cannot remove the workspace owner.
	WorkspaceRemoveMember bool `json:"workspaceRemoveMember"`
}

// GetWorkspaceRemoveMember returns removeWorkspaceMemberResponse.WorkspaceRemoveMember, and is useful for accessing the field via an interface.
func (v *removeWorkspaceMemberResponse) GetWorkspaceRemoveMember() bool {
	return v.WorkspaceRemoveMember
}

// revokeInviteResponse is returned by revokeInvite on success.
type revokeInviteResponse struct {
	// Revoke a pending outgoing invite. Requires admin or owner role.
	WorkspaceRevokeInvite bool `json:"workspaceRevokeInvite"`
}

// GetWorkspaceRevokeInvite returns revokeInviteResponse.WorkspaceRevokeInvite, and is useful for accessing the field via an interface.
func (v *revokeInviteResponse) GetWorkspaceRevokeInvite() bool { return v.WorkspaceRevokeInvite }

// sendChatMessageResponse is returned by sendChatMessage on success.
type sendChatMessageResponse struct {
	// Send a message to workspace chat. Messages are visible to all workspace members. Use channel for project-scoped discussions.
	ChatSend SendChatResult `json:"chatSend"`
}

// GetChatSend returns sendChatMessageResponse.ChatSend, and is useful for accessing the field via an interface.
func (v *sendChatMessageResponse) GetChatSend() SendChatResult { return v.ChatSend }

// setSecretsResponse is returned by setSecrets on success.
type setSecretsResponse struct {
	// Set env vars on a service. Merges with existing — new values override, unmentioned vars are preserved. Triggers a redeploy.
	ServiceSetSecrets SetSecretsResult `json:"serviceSetSecrets"`
}

// GetServiceSetSecrets returns setSecretsResponse.ServiceSetSecrets, and is useful for accessing the field via an interface.
func (v *setSecretsResponse) GetServiceSetSecrets() SetSecretsResult { return v.ServiceSetSecrets }

// updateServiceResponse is returned by updateService on success.
type updateServiceResponse struct {
	// Update service configuration and trigger a redeployment. Only specified fields change. Can also redeploy without changes to pull latest code.
	ServiceUpdate UpdateServiceResult `json:"serviceUpdate"`
}

// GetServiceUpdate returns updateServiceResponse.ServiceUpdate, and is useful for accessing the field via an interface.
func (v *updateServiceResponse) GetServiceUpdate() UpdateServiceResult { return v.ServiceUpdate }

// The mutation executed by acceptInvite.
const acceptInvite_Operation = `
mutation acceptInvite ($id: ID!) {
	workspaceAcceptInvite(inviteId: $id)
}
`

func acceptInvite(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *acceptInviteResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "acceptInvite",
		Query:  acceptInvite_Operation,
		Variables: &__acceptInviteInput{
			Id: id,
		},
	}

	data_ = &acceptInviteResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by addDNSRecord.
const addDNSRecord_Operation = `
mutation addDNSRecord ($zone: String!, $name: String!, $recordType: String!, $content: String!, $ttl: Int, $ws: String) {
	dnsAddRecord(zone: $zone, name: $name, type: $recordType, content: $content, ttl: $ttl, workspaceSlug: $ws) {
		id
		name
		type
		content
		ttl
		managed
		createdAt
	}
}
`

func addDNSRecord(
	ctx_ context.Context,
	client_ graphql.Client,
	zone string,
	name string,
	recordType string,
	content string,
	ttl *int,
	ws *string,
) (data_ *addDNSRecordResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "addDNSRecord",
		Query:  addDNSRecord_Operation,
		Variables: &__addDNSRecordInput{
			Zone:       zone,
			Name:       name,
			RecordType: recordType,
			Content:    content,
			Ttl:        ttl,
			Ws:         ws,
		},
	}

	data_ = &addDNSRecordResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by addDomain.
const addDomain_Operation = `
mutation addDomain ($name: String!, $domain: String!, $project: String, $ws: String) {
	domainAdd(name: $name, domain: $domain, project: $project, workspaceSlug: $ws) {
		serviceId
		domain
		status
		message
	}
}
`

func addDomain(
	ctx_ context.Context,
	client_ graphql.Client,
	name string,
	domain string,
	project *string,
	ws *string,
) (data_ *addDomainResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "addDomain",
		Query:  addDomain_Operation,
		Variables: &__addDomainInput{
			Name:    name,
			Domain:  domain,
			Project: project,
			Ws:      ws,
		},
	}

	data_ = &addDomainResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by createProject.
const createProject_Operation = `
mutation createProject ($input: CreateProjectInput!) {
	projectCreate(input: $input) {
		id
		name
		slug
		createdAt
		updatedAt
	}
}
`

func createProject(
	ctx_ context.Context,
	client_ graphql.Client,
	input CreateProjectInput,
) (data_ *createProjectResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "createProject",
		Query:  createProject_Operation,
		Variables: &__createProjectInput{
			Input: input,
		},
	}

	data_ = &createProjectResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by createRepo.
const createRepo_Operation = `
mutation createRepo ($input: RepoCreateInput!) {
	repoCreate(input: $input) {
		name
		gitRemote
		expiresAt
		message
	}
}
`

func createRepo(
	ctx_ context.Context,
	client_ graphql.Client,
	input CreateRepoInput,
) (data_ *createRepoResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "createRepo",
		Query:  createRepo_Operation,
		Variables: &__createRepoInput{
			Input: input,
		},
	}

	data_ = &createRepoResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by createService.
const createService_Operation = `
mutation createService ($input: CreateServiceInput!) {
	serviceCreate(input: $input) {
		serviceId
		name
		status
		repo
		ports {
			name
			port
			protocol
			visibility
			internalEndpoint
			publicEndpoint
		}
	}
}
`

func createService(
	ctx_ context.Context,
	client_ graphql.Client,
	input CreateServiceInput,
) (data_ *createServiceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "createService",
		Query:  createService_Operation,
		Variables: &__createServiceInput{
			Input: input,
		},
	}

	data_ = &createServiceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by createWorkspace.
const createWorkspace_Operation = `
mutation createWorkspace ($name: String!, $slug: String!, $description: String) {
	workspaceCreate(name: $name, slug: $slug, description: $description) {
		id
		name
		slug
		isDefault
		role
		createdAt
	}
}
`

func createWorkspace(
	ctx_ context.Context,
	client_ graphql.Client,
	name string,
	slug string,
	description *string,
) (data_ *createWorkspaceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "createWorkspace",
		Query:  createWorkspace_Operation,
		Variables: &__createWorkspaceInput{
			Name:        name,
			Slug:        slug,
			Description: description,
		},
	}

	data_ = &createWorkspaceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by declineInvite.
const declineInvite_Operation = `
mutation declineInvite ($id: ID!) {
	workspaceDeclineInvite(inviteId: $id)
}
`

func declineInvite(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *declineInviteResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "declineInvite",
		Query:  declineInvite_Operation,
		Variables: &__declineInviteInput{
			Id: id,
		},
	}

	data_ = &declineInviteResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by deleteDNSRecord.
const deleteDNSRecord_Operation = `
mutation deleteDNSRecord ($zone: String!, $recordId: ID!, $ws: String) {
	dnsDeleteRecord(zone: $zone, recordId: $recordId, workspaceSlug: $ws)
}
`

func deleteDNSRecord(
	ctx_ context.Context,
	client_ graphql.Client,
	zone string,
	recordId string,
	ws *string,
) (data_ *deleteDNSRecordResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "deleteDNSRecord",
		Query:  deleteDNSRecord_Operation,
		Variables: &__deleteDNSRecordInput{
			Zone:     zone,
			RecordId: recordId,
			Ws:       ws,
		},
	}

	data_ = &deleteDNSRecordResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by deleteProject.
const deleteProject_Operation = `
mutation deleteProject ($slug: String!, $ws: String) {
	projectDelete(slug: $slug, workspaceSlug: $ws)
}
`

func deleteProject(
	ctx_ context.Context,
	client_ graphql.Client,
	slug string,
	ws *string,
) (data_ *deleteProjectResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "deleteProject",
		Query:  deleteProject_Operation,
		Variables: &__deleteProjectInput{
			Slug: slug,
			Ws:   ws,
		},
	}

	data_ = &deleteProjectResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by deleteSecrets.
const deleteSecrets_Operation = `
mutation deleteSecrets ($input: DeleteSecretsInput!) {
	serviceDeleteSecrets(input: $input) {
		serviceId
		name
		status
	}
}
`

func deleteSecrets(
	ctx_ context.Context,
	client_ graphql.Client,
	input DeleteSecretsInput,
) (data_ *deleteSecretsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "deleteSecrets",
		Query:  deleteSecrets_Operation,
		Variables: &__deleteSecretsInput{
			Input: input,
		},
	}

	data_ = &deleteSecretsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by deleteService.
const deleteService_Operation = `
mutation deleteService ($name: String, $serviceId: ID, $project: String, $projectId: ID, $ws: String) {
	serviceDelete(name: $name, serviceId: $serviceId, project: $project, projectId: $projectId, workspaceSlug: $ws) {
		serviceId
		name
		message
	}
}
`

func deleteService(
	ctx_ context.Context,
	client_ graphql.Client,
	name *string,
	serviceId *string,
	project *string,
	projectId *string,
	ws *string,
) (data_ *deleteServiceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "deleteService",
		Query:  deleteService_Operation,
		Variables: &__deleteServiceInput{
			Name:      name,
			ServiceId: serviceId,
			Project:   project,
			ProjectId: projectId,
			Ws:        ws,
		},
	}

	data_ = &deleteServiceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by deleteWorkspace.
const deleteWorkspace_Operation = `
mutation deleteWorkspace ($id: ID!) {
	workspaceDelete(id: $id)
}
`

func deleteWorkspace(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *deleteWorkspaceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "deleteWorkspace",
		Query:  deleteWorkspace_Operation,
		Variables: &__deleteWorkspaceInput{
			Id: id,
		},
	}

	data_ = &deleteWorkspaceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by deployTemplate.
const deployTemplate_Operation = `
mutation deployTemplate ($input: TemplateDeployInput!) {
	templateDeploy(input: $input) {
		templateInstanceId
		projectId
		services {
			serviceId
			key
			name
			status
			endpoints {
				name
				port
				protocol
				visibility
				internalEndpoint
				publicEndpoint
			}
		}
		outputs {
			key
			label
			description
			kind
			sensitive
			value
		}
	}
}
`

func deployTemplate(
	ctx_ context.Context,
	client_ graphql.Client,
	input TemplateDeployInput,
) (data_ *deployTemplateResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "deployTemplate",
		Query:  deployTemplate_Operation,
		Variables: &__deployTemplateInput{
			Input: input,
		},
	}

	data_ = &deployTemplateResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by execService.
const execService_Operation = `
query execService ($serviceId: ID, $name: String, $command: String!, $project: String, $ws: String) {
	serviceExec(serviceId: $serviceId, name: $name, command: $command, project: $project, workspaceSlug: $ws) {
		exitCode
		stdout
		stderr
	}
}
`

func execService(
	ctx_ context.Context,
	client_ graphql.Client,
	serviceId *string,
	name *string,
	command string,
	project *string,
	ws *string,
) (data_ *execServiceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "execService",
		Query:  execService_Operation,
		Variables: &__execServiceInput{
			ServiceId: serviceId,
			Name:      name,
			Command:   command,
			Project:   project,
			Ws:        ws,
		},
	}

	data_ = &execServiceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by getAccountStatus.
const getAccountStatus_Operation = `
query getAccountStatus {
	accountStatus {
		id
		email
		displayName
		username
		githubUsername
		hasGitHubOAuth
		hasGitHubApp
		defaultWorkspace
		subscriptionTier
	}
}
`

func getAccountStatus(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *getAccountStatusResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "getAccountStatus",
		Query:  getAccountStatus_Operation,
	}

	data_ = &getAccountStatusResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by getRepoToken.
const getRepoToken_Operation = `
mutation getRepoToken ($input: RepoGetTokenInput!) {
	repoGetToken(input: $input) {
		gitRemote
		expiresAt
	}
}
`

func getRepoToken(
	ctx_ context.Context,
	client_ graphql.Client,
	input GetRepoTokenInput,
) (data_ *getRepoTokenResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "getRepoToken",
		Query:  getRepoToken_Operation,
		Variables: &__getRepoTokenInput{
			Input: input,
		},
	}

	data_ = &getRepoTokenResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by getService.
const getService_Operation = `
query getService ($id: ID!) {
	serviceGet(id: $id) {
		id
		projectId
		name
		subdomain
		source
		repo
		image
		branch
		status
		errorMessage
		envVars {
			key
			value
		}
		ports {
			name
			port
			protocol
			visibility
			internalEndpoint
			publicEndpoint
		}
		gitProvider
		commitHash
		memory
		vcpus
		customDomain
		customDomainStatus
		buildPack
		buildCommand
		startCommand
		publishDirectory
		rootDirectory
		dockerfilePath
		teardownEnabled
		teardownOverlapSeconds
		teardownDrainingSeconds
		destroyTimeoutSeconds
		createdAt
		updatedAt
	}
}
`

func getService(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *getServiceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "getService",
		Query:  getService_Operation,
		Variables: &__getServiceInput{
			Id: id,
		},
	}

	data_ = &getServiceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by getServiceExecUrl.
const getServiceExecUrl_Operation = `
query getServiceExecUrl ($serviceId: ID!) {
	serviceExecUrl(serviceId: $serviceId) {
		url
		token
		serviceId
	}
}
`

func getServiceExecUrl(
	ctx_ context.Context,
	client_ graphql.Client,
	serviceId string,
) (data_ *getServiceExecUrlResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "getServiceExecUrl",
		Query:  getServiceExecUrl_Operation,
		Variables: &__getServiceExecUrlInput{
			ServiceId: serviceId,
		},
	}

	data_ = &getServiceExecUrlResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by getServiceLogs.
const getServiceLogs_Operation = `
query getServiceLogs ($input: LogsInput!) {
	serviceLogs(input: $input) {
		entries {
			timestamp
			level
			message
			attributes
		}
		hasMore
	}
}
`

func getServiceLogs(
	ctx_ context.Context,
	client_ graphql.Client,
	input LogsInput,
) (data_ *getServiceLogsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "getServiceLogs",
		Query:  getServiceLogs_Operation,
		Variables: &__getServiceLogsInput{
			Input: input,
		},
	}

	data_ = &getServiceLogsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by getServiceMetrics.
const getServiceMetrics_Operation = `
query getServiceMetrics ($serviceId: ID!, $timeRange: MetricTimeRange!, $maxDataPoints: Int) {
	serviceMetrics(serviceId: $serviceId, timeRange: $timeRange, maxDataPoints: $maxDataPoints) {
		cpuUsage {
			metric
			dataPoints {
				timestamp
				value
			}
		}
		memoryUsageMB {
			metric
			dataPoints {
				timestamp
				value
			}
		}
		networkReceiveBytesPerSec {
			metric
			dataPoints {
				timestamp
				value
			}
		}
		networkTransmitBytesPerSec {
			metric
			dataPoints {
				timestamp
				value
			}
		}
		memoryLimitMB
		cpuLimitVCPUs
		diskUsageMB {
			metric
			dataPoints {
				timestamp
				value
			}
		}
		volumeSizeGi
	}
}
`

func getServiceMetrics(
	ctx_ context.Context,
	client_ graphql.Client,
	serviceId string,
	timeRange MetricTimeRange,
	maxDataPoints *int,
) (data_ *getServiceMetricsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "getServiceMetrics",
		Query:  getServiceMetrics_Operation,
		Variables: &__getServiceMetricsInput{
			ServiceId:     serviceId,
			TimeRange:     timeRange,
			MaxDataPoints: maxDataPoints,
		},
	}

	data_ = &getServiceMetricsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by getUsageBillBreakdown.
const getUsageBillBreakdown_Operation = `
query getUsageBillBreakdown ($ws: String) {
	usageBillBreakdown(workspaceSlug: $ws) {
		memory {
			quantity
			unitPrice
			unit
			totalCents
		}
		cpu {
			quantity
			unitPrice
			unit
			totalCents
		}
		egress {
			quantity
			unitPrice
			unit
			totalCents
		}
		subtotal
		includedUsageCents
		planFeeCents
		currentBillCents
		periodStart
		periodEnd
	}
}
`

func getUsageBillBreakdown(
	ctx_ context.Context,
	client_ graphql.Client,
	ws *string,
) (data_ *getUsageBillBreakdownResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "getUsageBillBreakdown",
		Query:  getUsageBillBreakdown_Operation,
		Variables: &__getUsageBillBreakdownInput{
			Ws: ws,
		},
	}

	data_ = &getUsageBillBreakdownResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by inviteToWorkspace.
const inviteToWorkspace_Operation = `
mutation inviteToWorkspace ($id: ID!, $user: String!, $role: String) {
	workspaceInvite(workspaceId: $id, user: $user, role: $role) {
		id
		workspaceId
		workspaceName
		workspaceSlug
		inviterDisplayName
		inviteeDisplayName
		role
		status
		createdAt
	}
}
`

func inviteToWorkspace(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
	user string,
	role *string,
) (data_ *inviteToWorkspaceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "inviteToWorkspace",
		Query:  inviteToWorkspace_Operation,
		Variables: &__inviteToWorkspaceInput{
			Id:   id,
			User: user,
			Role: role,
		},
	}

	data_ = &inviteToWorkspaceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by listDNSRecords.
const listDNSRecords_Operation = `
query listDNSRecords ($zone: String!, $ws: String) {
	dnsListRecords(zone: $zone, workspaceSlug: $ws) {
		id
		name
		type
		content
		ttl
		managed
		createdAt
	}
}
`

func listDNSRecords(
	ctx_ context.Context,
	client_ graphql.Client,
	zone string,
	ws *string,
) (data_ *listDNSRecordsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "listDNSRecords",
		Query:  listDNSRecords_Operation,
		Variables: &__listDNSRecordsInput{
			Zone: zone,
			Ws:   ws,
		},
	}

	data_ = &listDNSRecordsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by listDNSZones.
const listDNSZones_Operation = `
query listDNSZones ($ws: String) {
	dnsListZones(workspaceSlug: $ws) {
		id
		zone
		status
		error
		createdAt
	}
}
`

func listDNSZones(
	ctx_ context.Context,
	client_ graphql.Client,
	ws *string,
) (data_ *listDNSZonesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "listDNSZones",
		Query:  listDNSZones_Operation,
		Variables: &__listDNSZonesInput{
			Ws: ws,
		},
	}

	data_ = &listDNSZonesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by listMyInvites.
const listMyInvites_Operation = `
query listMyInvites {
	workspaceListMyInvites {
		id
		workspaceId
		workspaceName
		workspaceSlug
		inviterDisplayName
		inviteeDisplayName
		role
		status
		createdAt
	}
}
`

func listMyInvites(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *listMyInvitesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "listMyInvites",
		Query:  listMyInvites_Operation,
	}

	data_ = &listMyInvitesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by listProjects.
const listProjects_Operation = `
query listProjects ($ws: String) {
	projectList(workspaceSlug: $ws) {
		nodes {
			id
			name
			slug
			createdAt
			updatedAt
		}
	}
}
`

func listProjects(
	ctx_ context.Context,
	client_ graphql.Client,
	ws *string,
) (data_ *listProjectsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "listProjects",
		Query:  listProjects_Operation,
		Variables: &__listProjectsInput{
			Ws: ws,
		},
	}

	data_ = &listProjectsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by listServices.
const listServices_Operation = `
query listServices ($ws: String, $proj: String) {
	serviceList(workspaceSlug: $ws, projectSlug: $proj) {
		nodes {
			id
			projectId
			name
			subdomain
			source
			repo
			image
			branch
			status
			errorMessage
			envVars {
				key
				value
			}
			ports {
				name
				port
				protocol
				visibility
				internalEndpoint
				publicEndpoint
			}
			gitProvider
			commitHash
			memory
			vcpus
			customDomain
			customDomainStatus
			buildPack
			buildCommand
			startCommand
			publishDirectory
			rootDirectory
			dockerfilePath
			teardownEnabled
			teardownOverlapSeconds
			teardownDrainingSeconds
			destroyTimeoutSeconds
			createdAt
			updatedAt
		}
	}
}
`

func listServices(
	ctx_ context.Context,
	client_ graphql.Client,
	ws *string,
	proj *string,
) (data_ *listServicesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "listServices",
		Query:  listServices_Operation,
		Variables: &__listServicesInput{
			Ws:   ws,
			Proj: proj,
		},
	}

	data_ = &listServicesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by listTemplateInstances.
const listTemplateInstances_Operation = `
query listTemplateInstances ($project: String, $projectId: ID, $ws: String) {
	templateInstanceList(project: $project, projectId: $projectId, workspaceSlug: $ws) {
		id
		templateSlug
		projectId
		name
		status
		services {
			serviceId
			key
			name
			status
			endpoints {
				name
				port
				protocol
				visibility
				internalEndpoint
				publicEndpoint
			}
		}
		outputs {
			key
			label
			description
			kind
			sensitive
			value
		}
		createdAt
	}
}
`

func listTemplateInstances(
	ctx_ context.Context,
	client_ graphql.Client,
	project *string,
	projectId *string,
	ws *string,
) (data_ *listTemplateInstancesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "listTemplateInstances",
		Query:  listTemplateInstances_Operation,
		Variables: &__listTemplateInstancesInput{
			Project:   project,
			ProjectId: projectId,
			Ws:        ws,
		},
	}

	data_ = &listTemplateInstancesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by listTemplates.
const listTemplates_Operation = `
query listTemplates ($search: String) {
	templateList(search: $search) {
		slug
		name
		description
		tags
		icon
		variables {
			key
			type
			name
			description
			required
			sensitive
			defaultValue
			options
		}
		services {
			key
			name
			source
			image
			memory
			vcpus
		}
		outputs {
			key
			label
			description
			kind
			sensitive
		}
	}
}
`

func listTemplates(
	ctx_ context.Context,
	client_ graphql.Client,
	search *string,
) (data_ *listTemplatesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "listTemplates",
		Query:  listTemplates_Operation,
		Variables: &__listTemplatesInput{
			Search: search,
		},
	}

	data_ = &listTemplatesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by listWorkspaceInvites.
const listWorkspaceInvites_Operation = `
query listWorkspaceInvites ($slug: String!) {
	workspaceListInvites(workspaceSlug: $slug) {
		id
		workspaceId
		workspaceName
		workspaceSlug
		inviterDisplayName
		inviteeDisplayName
		role
		status
		createdAt
	}
}
`

func listWorkspaceInvites(
	ctx_ context.Context,
	client_ graphql.Client,
	slug string,
) (data_ *listWorkspaceInvitesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "listWorkspaceInvites",
		Query:  listWorkspaceInvites_Operation,
		Variables: &__listWorkspaceInvitesInput{
			Slug: slug,
		},
	}

	data_ = &listWorkspaceInvitesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by listWorkspaceMembers.
const listWorkspaceMembers_Operation = `
query listWorkspaceMembers ($slug: String!) {
	workspaceListMembers(workspaceSlug: $slug) {
		id
		userId
		email
		username
		displayName
		avatarUrl
		role
		joinedAt
	}
}
`

func listWorkspaceMembers(
	ctx_ context.Context,
	client_ graphql.Client,
	slug string,
) (data_ *listWorkspaceMembersResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "listWorkspaceMembers",
		Query:  listWorkspaceMembers_Operation,
		Variables: &__listWorkspaceMembersInput{
			Slug: slug,
		},
	}

	data_ = &listWorkspaceMembersResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by listWorkspaces.
const listWorkspaces_Operation = `
query listWorkspaces {
	workspaceList {
		id
		name
		slug
		isDefault
		role
		createdAt
	}
}
`

func listWorkspaces(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *listWorkspacesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "listWorkspaces",
		Query:  listWorkspaces_Operation,
	}

	data_ = &listWorkspacesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by readChat.
const readChat_Operation = `
query readChat ($ws: String!, $channel: String, $cursor: Int, $limit: Int) {
	chatRead(workspaceSlug: $ws, channel: $channel, cursor: $cursor, limit: $limit) {
		messages {
			seq
			messageId
			senderId
			senderName
			channel
			content
			metadata
			createdAt
		}
		nextCursor
		hasMore
	}
}
`

func readChat(
	ctx_ context.Context,
	client_ graphql.Client,
	ws string,
	channel *string,
	cursor *int,
	limit *int,
) (data_ *readChatResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "readChat",
		Query:  readChat_Operation,
		Variables: &__readChatInput{
			Ws:      ws,
			Channel: channel,
			Cursor:  cursor,
			Limit:   limit,
		},
	}

	data_ = &readChatResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by removeDomain.
const removeDomain_Operation = `
mutation removeDomain ($name: String!, $project: String, $ws: String) {
	domainRemove(name: $name, project: $project, workspaceSlug: $ws) {
		serviceId
		message
	}
}
`

func removeDomain(
	ctx_ context.Context,
	client_ graphql.Client,
	name string,
	project *string,
	ws *string,
) (data_ *removeDomainResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "removeDomain",
		Query:  removeDomain_Operation,
		Variables: &__removeDomainInput{
			Name:    name,
			Project: project,
			Ws:      ws,
		},
	}

	data_ = &removeDomainResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by removeWorkspaceMember.
const removeWorkspaceMember_Operation = `
mutation removeWorkspaceMember ($wsId: ID!, $userId: ID!) {
	workspaceRemoveMember(workspaceId: $wsId, userId: $userId)
}
`

func removeWorkspaceMember(
	ctx_ context.Context,
	client_ graphql.Client,
	wsId string,
	userId string,
) (data_ *removeWorkspaceMemberResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "removeWorkspaceMember",
		Query:  removeWorkspaceMember_Operation,
		Variables: &__removeWorkspaceMemberInput{
			WsId:   wsId,
			UserId: userId,
		},
	}

	data_ = &removeWorkspaceMemberResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by revokeInvite.
const revokeInvite_Operation = `
mutation revokeInvite ($id: ID!) {
	workspaceRevokeInvite(inviteId: $id)
}
`

func revokeInvite(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *revokeInviteResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "revokeInvite",
		Query:  revokeInvite_Operation,
		Variables: &__revokeInviteInput{
			Id: id,
		},
	}

	data_ = &revokeInviteResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by sendChatMessage.
const sendChatMessage_Operation = `
mutation sendChatMessage ($ws: String!, $channel: String, $content: String!) {
	chatSend(workspaceSlug: $ws, channel: $channel, content: $content) {
		seq
		messageId
	}
}
`

func sendChatMessage(
	ctx_ context.Context,
	client_ graphql.Client,
	ws string,
	channel *string,
	content string,
) (data_ *sendChatMessageResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "sendChatMessage",
		Query:  sendChatMessage_Operation,
		Variables: &__sendChatMessageInput{
			Ws:      ws,
			Channel: channel,
			Content: content,
		},
	}

	data_ = &sendChatMessageResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by setSecrets.
const setSecrets_Operation = `
mutation setSecrets ($input: SetSecretsInput!) {
	serviceSetSecrets(input: $input) {
		serviceId
		name
		status
	}
}
`

func setSecrets(
	ctx_ context.Context,
	client_ graphql.Client,
	input SetSecretsInput,
) (data_ *setSecretsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "setSecrets",
		Query:  setSecrets_Operation,
		Variables: &__setSecretsInput{
			Input: input,
		},
	}

	data_ = &setSecretsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by updateService.
const updateService_Operation = `
mutation updateService ($input: UpdateServiceInput!) {
	serviceUpdate(input: $input) {
		serviceId
		name
		status
	}
}
`

func updateService(
	ctx_ context.Context,
	client_ graphql.Client,
	input UpdateServiceInput,
) (data_ *updateServiceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "updateService",
		Query:  updateService_Operation,
		Variables: &__updateServiceInput{
			Input: input,
		},
	}

	data_ = &updateServiceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
